import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { DEFAULT_PROGRESS, weeklyMessage, weightChange } from '../features/progress/progressModel';

const BASE = { background:'#020E18',surface:'#0C1B27',surfaceAlt:'#101F2B',border:'#1B3240',text:'#F3F7F8',muted:'#91A0AB',primary:'#5CE778',success:'#5CE778',warning:'#FFB22C' };
const palette = (theme) => ({ ...BASE, ...(theme?.colors || theme || {}) });
const Card = ({children,c,style}) => <View style={[s.card,{backgroundColor:c.surface,borderColor:c.border},style]}>{children}</View>;

export default function ProgressScreen({ theme, progressData = DEFAULT_PROGRESS }) {
  const c = palette(theme); const [range,setRange] = useState('7D'); const delta = weightChange(progressData.weight);
  return <View style={[s.root,{backgroundColor:c.background}]}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.header}><View><Text style={[s.title,{color:c.text}]}>Progress</Text><Text style={[s.subtitle,{color:c.muted}]}>Consistency over perfection</Text></View><TouchableOpacity style={[s.calendar,{borderColor:c.border}]}><Ionicons name="calendar-outline" size={21} color={c.text}/></TouchableOpacity></View>
    <View style={s.rangeRow}>{['7D','30D','90D','1Y','All'].map(label=><TouchableOpacity key={label} onPress={()=>setRange(label)} style={[s.range,range===label&&{backgroundColor:`${c.primary}22`}]}><Text style={[s.rangeText,{color:range===label?c.primary:c.muted}]}>{label}</Text></TouchableOpacity>)}</View>
    <Card c={c} style={s.recovery}><View style={[s.coachIcon,{backgroundColor:`${c.primary}22`}]}><Ionicons name="sparkles" size={20} color={c.primary}/></View><View style={{flex:1}}><Text style={[s.recoveryTitle,{color:c.text}]}>A steady week</Text><Text style={[s.recoveryText,{color:c.muted}]}>{weeklyMessage(progressData.compliance.nutrition)}</Text></View></Card>
    <Card c={c} style={s.chartCard}><View style={s.between}><View><Text style={[s.cardTitle,{color:c.text}]}>Weight trend</Text><Text style={[s.muted,{color:c.muted}]}>Rolling trend · {range}</Text></View><Text style={[s.delta,{color:delta<=0?c.success:c.warning}]}>{delta>0?'+':''}{delta} kg</Text></View><WeightChart values={progressData.weight} c={c}/><View style={s.chartFooter}><Text style={[s.muted,{color:c.muted}]}>Aug 2</Text><Text style={[s.current,{color:c.text}]}>{progressData.weight.at(-1)} kg</Text><Text style={[s.muted,{color:c.muted}]}>Aug 8</Text></View></Card>
    <Card c={c} style={s.overview}><View style={s.between}><Text style={[s.cardTitle,{color:c.text}]}>Nutrition consistency</Text><Text style={[s.muted,{color:c.muted}]}>This week</Text></View><View style={s.rings}>{[['Nutrition',progressData.compliance.nutrition,c.primary],['Protein',progressData.compliance.protein,c.warning],['Fiber',progressData.compliance.fiber,c.primary]].map(([label,value,color])=><Metric key={label} label={label} value={value} color={color} c={c}/>)}</View><View style={[s.note,{backgroundColor:c.surfaceAlt}]}><Ionicons name="information-circle-outline" size={18} color={c.primary}/><Text style={[s.noteText,{color:c.muted}]}>Your score shows how closely the week matched your targets. It is guidance, never pass or fail.</Text></View></Card>
    <Card c={c} style={s.habits}><View style={s.between}><Text style={[s.cardTitle,{color:c.text}]}>Helpful rhythms</Text><Text style={[s.muted,{color:c.muted}]}>This week</Text></View>{progressData.habits.map((habit,index)=><View key={habit.id} style={[s.habit,index>0&&{borderTopColor:c.border,borderTopWidth:StyleSheet.hairlineWidth}]}><View style={[s.habitIcon,{backgroundColor:`${habit.days>=5?c.success:c.warning}1C`}]}><Ionicons name={habit.icon} size={16} color={habit.days>=5?c.success:c.warning}/></View><Text style={[s.habitLabel,{color:c.text}]}>{habit.label}</Text><View style={s.dots}>{[1,2,3,4,5,6,7].map(day=><View key={day} style={[s.dot,{backgroundColor:day<=habit.days?(habit.days>=5?c.success:c.warning):c.border}]}/>)}</View><Text style={[s.days,{color:c.muted}]}>{habit.days}/7</Text></View>)}</Card>
    <TouchableOpacity style={[s.cta,{backgroundColor:c.primary}]}><Ionicons name="refresh" size={19} color="#04140A"/><Text style={s.ctaText}>Plan an easier recovery week</Text></TouchableOpacity>
  </ScrollView></View>;
}

function Metric({label,value,color,c}) { return <View style={s.metric}><View style={[s.ring,{borderColor:`${color}40`}]}><View style={[s.ringAccent,{borderColor:color}]}/><Text style={[s.ringValue,{color:c.text}]}>{value}%</Text></View><Text style={[s.metricLabel,{color:c.muted}]}>{label}</Text></View>; }
function WeightChart({values,c}) { const min=Math.min(...values)-.5,max=Math.max(...values)+.5,span=max-min||1; return <View style={s.chart}>{[20,50,80].map(top=><View key={top} style={[s.grid,{top:`${top}%`,backgroundColor:c.border}]}/>)}<View style={[s.area,{backgroundColor:`${c.primary}14`}]}/>{values.map((value,index)=>{const left=5+index*(90/(values.length-1)),top=12+((max-value)/span)*70;return <View key={`${value}-${index}`} style={[s.point,{left:`${left}%`,top:`${top}%`,backgroundColor:c.primary,borderColor:c.surface}]}/>;})}</View>; }

const s=StyleSheet.create({
  root:{flex:1},content:{paddingHorizontal:20,paddingTop:18,paddingBottom:130},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:16},title:{fontSize:28,fontWeight:'750'},subtitle:{fontSize:12,marginTop:4},calendar:{width:42,height:42,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center'},rangeRow:{flexDirection:'row',justifyContent:'space-between',marginBottom:15},range:{paddingHorizontal:15,paddingVertical:9,borderRadius:15},rangeText:{fontSize:12,fontWeight:'800'},card:{borderWidth:1,borderRadius:22},recovery:{padding:15,flexDirection:'row',alignItems:'center',gap:12,marginBottom:14},coachIcon:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center'},recoveryTitle:{fontSize:15,fontWeight:'800'},recoveryText:{fontSize:12,lineHeight:17,marginTop:3},chartCard:{padding:17,marginBottom:14},between:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},cardTitle:{fontSize:16,fontWeight:'750'},muted:{fontSize:11,marginTop:4},delta:{fontSize:17,fontWeight:'850'},chart:{height:155,marginTop:18,overflow:'hidden',position:'relative'},grid:{position:'absolute',left:0,right:0,height:StyleSheet.hairlineWidth},area:{position:'absolute',left:'4%',right:'4%',bottom:6,height:'55%',borderTopLeftRadius:70,borderTopRightRadius:70},point:{position:'absolute',width:11,height:11,borderRadius:6,borderWidth:3,marginLeft:-5,marginTop:-5},chartFooter:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},current:{fontSize:13,fontWeight:'800'},overview:{padding:17,marginBottom:14},rings:{flexDirection:'row',justifyContent:'space-around',marginTop:20},metric:{alignItems:'center'},ring:{width:78,height:78,borderRadius:39,borderWidth:7,alignItems:'center',justifyContent:'center'},ringAccent:{position:'absolute',width:78,height:78,borderRadius:39,borderWidth:7,borderLeftColor:'transparent',borderBottomColor:'transparent',transform:[{rotate:'25deg'}]},ringValue:{fontSize:19,fontWeight:'850'},metricLabel:{fontSize:11,fontWeight:'700',marginTop:8},note:{marginTop:18,borderRadius:14,padding:12,flexDirection:'row',gap:8},noteText:{fontSize:11,lineHeight:16,flex:1},habits:{paddingHorizontal:16,paddingTop:17,paddingBottom:7,marginBottom:14},habit:{minHeight:54,flexDirection:'row',alignItems:'center',gap:9},habitIcon:{width:29,height:29,borderRadius:10,alignItems:'center',justifyContent:'center'},habitLabel:{fontSize:12,fontWeight:'650',flex:1},dots:{flexDirection:'row',gap:4},dot:{width:8,height:8,borderRadius:4},days:{fontSize:10,width:28,textAlign:'right'},cta:{height:52,borderRadius:17,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},ctaText:{color:'#04140A',fontSize:14,fontWeight:'850'},
});
